# Generated by Django 4.2.6 on 2023-11-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
